spring.application.name=Wm26
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.admin.auto-create=false
spring.mongodb.uri=mongodb://root:example@localhost:27017/wm26?authSource=admin
spring.kafka.consumer.group-id=wm26-consumer-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.value.default.type=org.example.wm26.model.Match
spring.kafka.consumer.properties.spring.json.trusted.packages=*
